// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  program = 1,
  Assignment = 2,
  Number = 3,
  VariableName = 4,
  UnaryExpression = 5,
  BinaryExpression = 7,
  Exp = 8,
  Into = 12,
  into = 13,
  From = 16,
  from = 17,
  AsPercentOf = 21,
  apo = 22
