// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_word = {__proto__:null,into:26, from:34, apo:44}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$tOYQPOOOOQO'#C`'#C`OYQPO'#C|Q!iQQO'#C^OOQO'#Cz'#CzO!pQQO'#CzQOQPOOOYQPO'#CaO#zQQO,59hOOQO'#Cd'#CdOOQO'#Ch'#ChOOQO'#Cl'#ClOOQO'#Cq'#CqOYQPO,58}OYQPO,58}OYQPO,58}OYQPO,58}OOQO'#Ct'#CtO$RQPO,58xOOQO'#Cu'#CuOYQPO,58xOOQO,58{,58{OOQO1G/S1G/SOOQO1G.i1G.iO%OQQO1G.iO%fQQO1G.iO&wQQO1G.iOOQO1G.d1G.dO'[QQO1G.d",
  stateData: "'c~OlOSmOS~ORSOUVOoPOqQO~OU_OX^OY^OZ^O]YO^YO_YOaZObZOcZOdZOf[Og[OsXOtXO~OvaO~PhOwcOUnXXnXYnXZnX]nX^nX_nXanXbnXcnXdnXfnXgnXjnXsnXtnXvnX~OrfO~PhOoPO~OsXOtXOUViaVibVicVidVifVigVijVivVirVi~OXViYViZVi]Vi^Vi_Vi~P$WOX^OY^OZ^O]YO^YO_YO~P$WOU_OX^OY^OZ^O]YO^YO_YOaZObZOcZOdZOsXOtXO~OfVigVijVivVirVi~P%|OjQi~PhO",
  goto: "#jqPPrPu!UP!U!`PPP!hPPP!oPPPP!uPP!z!}PPPP#QP!URUO^SQV]^_`dQTORkbaSOQV]^_`d]]RWhijlZ^RWijlX_RWjlV`RWlRbRRdTQROQWQQeVQg]Qh^Qi_Qj`Rld",
  nodeNames: "⚠ program Assignment Number VariableName UnaryExpression ArithOp BinaryExpression Exp ArithOp ArithOp ArithOp Into into ArithOp ArithOp From from ArithOp ArithOp ArithOp AsPercentOf apo ArithOp Equals Equals",
  maxTerm: 39,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "&T~RdYZ!a]^!apq!fuv!nxy!{yz#Qz{#V{|#d}!O#d!P!Q#i!Q![#v![!]%R!^!_%W!_!`%]!c!}%b#O#P%o#Q#R%t#R#S%y#T#o%b#p#q&O~!fOm~~!kPl~pq!f~!sPZ~uv!v~!{Og~~#QOq~~#VOr~~#[PY~z{#_~#dOt~~#iOU~~#nPX~!P!Q#q~#vO_~~#{SR~!O!P$X!Q![#v!g!h$g#X#Y$g~$^RR~!Q![$X!g!h$g#X#Y$g~$jR{|$s}!O$s!Q![$y~$vP!Q![$y~%OPR~!Q![$y~%WOw~~%]Oc~~%bOv~R%iQoPuQ!c!}%b#T#o%b~%tO^~~%yOs~~&OOd~~&TOb~",
  tokenizers: [0, 1],
  topRules: {"program":[0,1]},
  specialized: [{term: 37, get: (value) => spec_word[value] || -1}],
  tokenPrec: 0
})
