// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  program = 1,
  Assignment = 2,
  Number = 3,
  VariableName = 4,
  UnaryExpression = 5,
  BinaryExpression = 7,
  Exp = 8,
  Mod = 11,
  mod = 12,
  Into = 13,
  into = 14,
  From = 17,
  from = 18,
  AsProportionOf = 22,
  apo = 23
